name: 应用请求
description: 推荐 Android TV 应用
title: "[应用请求]: "
labels: ["应用请求"]

body:
  - type: input
    id: app-name
    attributes:
      label: 应用名称
      placeholder: 例如：VLC（必填）
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: 应用源码
      placeholder: 例如：https://github.com/videolan/vlc-android（必填）
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: 应用分类
      placeholder: 例如：媒体播放器（必填）
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: 应用官网
      placeholder: 例如：https://www.videolan.org/vlc/（可选）
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: 应用描述
      placeholder: 例如：一款免费开源的跨平台媒体播放器（必填）
    validations:
      required: true
  - type: dropdown
    id: remote-support
    attributes:
      label: 遥控器支持
      description: 该应用界面是否完全支持标准遥控器操作？（方向键、音量键等）
      options:
        - "完全支持"
        - "部分支持"
    validations:
      required: true
  - type: dropdown
    id: launcher-icon
    attributes:
      label: 启动器图标
      description: 应用是否包含启动器图标？
      options:
        - "是"
        - "否"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 补充信息
      placeholder: 例如：某功能无法通过标准遥控器操作（可选）
    validations:
      required: false